---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# dbcti-paper

<!-- badges: start -->
<!-- badges: end -->

This repository contains the code for the dbcti-paper. Working directory should be set as dbcti-paper-master for running the codes. 

## Data structure
* `datasets` file contains simulated data included in the paper. Real datasets are too large to be included and are available at the corresponding GEO datasets. The folder is also the directory used for store the generated data from the analysis codes.
* `simulation_and_real_data` file contains codes for different tools constructing cell trajectories.
* `evaluation` file contains codes for evaluating performances of tools.
* `case_study` file contains codes for performing case study.

## File source
For files that are required in the code but not generated from other codes, please refer to the data availability section in the original paper.
